#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
OSYRIS vs VTK Profile Comparison and Validation

CLI tool to compare radial density profiles generated by OSYRIS and VTK 
processing pipelines. Computes Pearson correlation and Lin's Concordance Correlation 
Coefficient (CCC) to validate consistency between visualization backends.

Features:
- Loads paired Osyris (`osyris_profile_XXXXX.csv`) and VTK (`vtk_profile_XXXXX.csv`) profiles
- Generates publication-quality comparison plots with error bands
- Computes statistical validation metrics (correlation, CCC)
- HARDCODED output to ./profile_outputs/

CLI Usage:
    python3 analyzing_profiles.py -n 2
    python3 analyzing_profiles.py --number 2 --verbose
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import argparse
import logging
from pathlib import Path
from typing import Tuple

logger = logging.getLogger("profile_comparison")


def load_profile_data(osyris_file: str, vtk_file: str) -> Tuple[np.ndarray, np.ndarray]:
    """
    Load OSYRIS and VTK radial density profile CSV files.
    
    Args:
        osyris_file: Path to Osyris profile CSV (osyris_profile_XXXXX.csv)
        vtk_file: Path to VTK profile CSV (vtk_profile_XXXXX.csv)
        
    Returns:
        Tuple of (osyris_profile, vtk_profile) numpy arrays
        
    Raises:
        FileNotFoundError: If either CSV file is missing
    """
    if not os.path.isfile(osyris_file):
        raise FileNotFoundError(f"OSYRIS profile not found: {osyris_file}")
    
    if not os.path.isfile(vtk_file):
        raise FileNotFoundError(f"VTK profile not found: {vtk_file}")
    
    logger.info("Loading profile data from:\n  OSYRIS: %s\n  VTK: %s", 
                osyris_file, vtk_file)
    
    osyris_profile = np.loadtxt(osyris_file, delimiter=",")
    vtk_profile = np.loadtxt(vtk_file, delimiter=",")
    
    logger.info("Loaded profiles: OSYRIS(%d bins), VTK(%d bins)", 
                len(osyris_profile), len(vtk_profile))
    
    return osyris_profile, vtk_profile


def compute_validation_metrics(osyris_data: np.ndarray, vtk_data: np.ndarray) -> dict:
    """
    Compute statistical validation metrics between Osyris and VTK profiles.
    
    Args:
        osyris_data: Osyris profile data [n_bins, 5]
        vtk_data: VTK profile data [n_bins, 5]
        
    Returns:
        Dictionary containing Pearson correlation and CCC
    """
    # Truncate to common length
    n = min(len(osyris_data), len(vtk_data))
    d_osyris = osyris_data[:n, 1]  # Mean density column
    d_vtk = vtk_data[:n, 1]
    
    # Basic statistics
    mean_osyris = np.mean(d_osyris)
    var_osyris = np.var(d_osyris)
    std_osyris = np.std(d_osyris)
    
    mean_vtk = np.mean(d_vtk)
    var_vtk = np.var(d_vtk)
    std_vtk = np.std(d_vtk)
    
    # Pearson correlation coefficient
    cor = np.corrcoef(d_osyris, d_vtk)[0, 1]
    
    # Concordance Correlation Coefficient (CCC)
    numerator = 2 * cor * std_osyris * std_vtk
    denominator = var_osyris + var_vtk + (mean_osyris - mean_vtk)**2
    ccc = numerator / denominator if denominator != 0 else np.nan
    
    return {
        'pearson_r': cor,
        'ccc': ccc,
        'mean_osyris': mean_osyris,
        'mean_vtk': mean_vtk,
        'n_bins': n
    }


def create_comparison_plot(osyris_profile: np.ndarray, vtk_profile: np.ndarray, 
                         output_path: str, output_number: int) -> None:
    """
    Generate publication-quality comparison plot with error bands.
    
    Args:
        osyris_profile: Osyris profile data [radius, mean, std, min, max]
        vtk_profile: VTK profile data [radius, mean, std, min, max]
        output_path: Path to save PNG
        output_number: Snapshot number for filename
    """
    fig, ax = plt.subplots(figsize=(6, 4), dpi=300)
    
    # OSYRIS profile (dashed blue)
    ax.plot(osyris_profile[:,0], osyris_profile[:,1],
            linewidth=1.5, linestyle="--", color="blue", alpha=0.9,
            label="Osyris", zorder=3)
    ax.fill_between(osyris_profile[:,0], osyris_profile[:,3], osyris_profile[:,4],
                    alpha=0.2, color="blue", label="Osyris range")
    
    # VTK profile (dash-dot red)
    ax.plot(vtk_profile[:,0], vtk_profile[:,1],
            linewidth=1.5, linestyle="-.", color="red", alpha=0.9,
            label="VTK/Chhavi", zorder=3)
    ax.fill_between(vtk_profile[:,0], vtk_profile[:,3], vtk_profile[:,4],
                    alpha=0.2, color="red", label="VTK/Chhavi range")
    
    # Formatting
    ax.set_xlim(0, 0.2)
    ax.set_ylim(0, 2.25)
    ax.set_xlabel(r"Radius [$cm$]")
    ax.set_ylabel(r"Density [$g\,cm^{-3}$]") 
    ax.grid(True, alpha=0.3)
    ax.legend(framealpha=0.95)
    ax.set_title(f"Snapshot {output_number:05d}: OSYRIS vs VTK Profiles")
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close()
    logger.info("Saved comparison plot: %s", output_path)


def main() -> None:
    """
    CLI entrypoint for OSYRIS-VTK profile comparison.
    """
    parser = argparse.ArgumentParser(
        description="Compare OSYRIS vs VTK radial density profiles",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument("-n", "--number", type=int, required=True,
                       help="Snapshot number (e.g., 2 for output_00002)")
    parser.add_argument("--verbose", action="store_true", 
                       help="Enable detailed logging")

    args = parser.parse_args()
    
    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s"
    )
    
    # HARDCODED: Always ./profile_outputs/
    output_dir = Path("profile_outputs")
    osyris_file = output_dir / f"osyris_profile_{args.number:05d}.csv" 
    vtk_file = output_dir / f"vtk_profile_{args.number:05d}.csv"       
    plot_path = output_dir / f"profile_comparison_{args.number:05d}.png"
    
    logger.info("Comparing snapshot %05d", args.number)
    logger.info("Input files:\n  OSYRIS: %s\n  VTK: %s", osyris_file, vtk_file)
    
    try:
        # Ensure output directory exists
        os.makedirs(output_dir, exist_ok=True)
        
        # Load profile data
        osyris_profile, vtk_profile = load_profile_data(str(osyris_file), str(vtk_file))
        
        # Create comparison plot
        create_comparison_plot(osyris_profile, vtk_profile, str(plot_path), args.number)
        
        # Compute validation metrics
        metrics = compute_validation_metrics(osyris_profile, vtk_profile)
        
        # Print results
        print("\n" + "="*50)  
        print(f"SNAPSHOT VALIDATION RESULTS: {args.number:05d}")
        print("="*50)
        print(f"Pearson Correlation (r):  {metrics['pearson_r']:.6f}")
        print(f"Concordance CCC:          {metrics['ccc']:.6f}")
        print(f"Mean OSYRIS:              {metrics['mean_osyris']:.4f}")
        print(f"Mean VTK:                 {metrics['mean_vtk']:.4f}")
        print(f"Common bins analyzed:     {metrics['n_bins']}")
        print("="*50)
        
        logger.info("Analysis complete. Plot saved: %s", plot_path)
        
    except FileNotFoundError as e:
        logger.error("Missing input files: %s", e)
    except Exception as e:
        logger.exception("Analysis failed")


if __name__ == "__main__":
    main()
