#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
VTK Radial Density Profile Generator

CLI tool to compute radial density profiles from VTKHDF files generated by 
RAMSES-to-VTKHDF converter (Chhavi). Processes AMR hierarchy blocks to extract 
cell-centered density values and compute spherical shell statistics.

Features:
- Cross-platform: Windows (serial), Linux/macOS (parallel multiprocessing)
- Processes complete AMR hierarchy across all levels
- Computes mean/std/min/max density per unique radial distance
- Smart CLI with auto-detection of available snapshots (ANY *.vtkhdf prefix!)
- Saves vtk_profile_XXXXX.csv to ./profile_outputs/ (HARDCODED)

CLI Usage:
    python3 compute_vtk_profile.py --base-dir ../vtk_outputs --folder-name sedov_3d
    python3 compute_vtk_profile.py --base-dir ../vtk_outputs --folder-name sedov_3d -n 1,5
"""

import os
import re
import argparse
import logging
import numpy as np
from pathlib import Path
from typing import List
from multiprocessing import Pool
import vtk
from vtk.util import numpy_support

logger = logging.getLogger("vtk_profiles")


def parse_output_numbers(value: str) -> List[int]:
    """
    Parse CLI output numbers string into list of integers.
    
    Supports formats: "1", "1,3,5", "10-15".
    
    Args:
        value: Input string from CLI argument
        
    Returns:
        Sorted list of unique output numbers
        
    Raises:
        argparse.ArgumentTypeError: If parsing fails
    """
    numbers = set()
    parts = value.split(",")
    
    for part in parts:
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            try:
                start, end = map(int, re.findall(r"\d+", part)) 
                numbers.update(range(start, end + 1))
            except ValueError:
                raise argparse.ArgumentTypeError(f"Invalid range '{part}'")
        else:
            try:
                numbers.add(int(part))
            except ValueError:
                raise argparse.ArgumentTypeError(f"Invalid number '{part}'")
    
    if not numbers:
        raise argparse.ArgumentTypeError(f"No valid numbers in: {value}")
    return sorted(list(numbers))


def detect_vtk_files(base_dir: str, folder_name: str) -> List[int]:
    """
    Scan VTK output folder for ANY *.vtkhdf files and extract 5-digit numbers.
    
    Works with ANY prefix: sedov_test_00001.vtkhdf, myrun_00001.vtkhdf, etc.
    
    Args:
        base_dir: Root directory containing VTK output folders
        folder_name: VTK simulation folder name
        
    Returns:
        Sorted list of available output numbers
    """
    folder_path = Path(base_dir) / folder_name
    logger.info("Scanning VTK files: %s", folder_path)
    
    if not folder_path.exists():
        logger.warning("VTK folder not found: %s", folder_path)
        return []

    pattern = re.compile(r".*?(\d{5})\.vtkhdf$")
    outputs = []
    
    try:
        for item in folder_path.iterdir():
            if item.suffix == '.vtkhdf':  # Only VTKHDF files
                match = pattern.search(item.name)
                if match:
                    outputs.append(int(match.group(1)))
        outputs.sort()
        if outputs:
            logger.info("Found %d VTK files: %s", 
                       len(outputs), 
                       outputs[:5] + ["..."] if len(outputs) > 5 else outputs)
            logger.debug("Detected files: %s", [f"{n:05d}.vtkhdf" for n in outputs[:3]])
        else:
            logger.warning("No *.vtkhdf files found")
    except PermissionError:
        logger.error("Permission denied: %s", folder_path)
    
    return outputs


def match_short_numbers(numbers: List[int], available: List[int]) -> List[int]:
    """
    Match user-specified short numbers to available 5-digit VTK files.
    
    Args:
        numbers: User-specified output numbers
        available: All detected output numbers
        
    Returns:
        List of matching output numbers
    """
    matched = []
    for n in numbers:
        n_str = str(n)
        if len(n_str) >= 3:
            if n in available:
                matched.append(n)
        else:
            for pad_len in [5, 4, 3]:
                padded = int(f"{n:0{pad_len}d}")
                if padded in available:
                    matched.append(padded)
                    break
    return sorted(set(matched))


def find_actual_vtk_file(folder_path: str, output_number: int) -> str:
    """
    Find actual VTK file matching the 5-digit output number.
    
    Args:
        folder_path: Directory containing VTK files
        output_number: 5-digit output number
        
    Returns:
        Full path to matching *.vtkhdf file
    """
    pattern = re.compile(rf".*?{output_number:05d}\.vtkhdf$")
    folder = Path(folder_path)
    
    for item in folder.iterdir():
        if item.suffix == '.vtkhdf' and pattern.search(item.name):
            logger.debug("Found VTK file: %s", item.name)
            return str(item)
    
    raise FileNotFoundError(f"No *.vtkhdf file found for output_{output_number:05d}")


def find_density_cell(num: int, data: vtk.vtkMultiBlockDataSet, level: int):
    """
    Extract density value and radial distance for single AMR block.
    
    Args:
        num: Block index within level
        data: VTK dataset
        level: AMR refinement level
        
    Returns:
        Array [density_value, radial_distance]
    """
    amr_box = data.GetDataSet(level, num)
    if amr_box is None:
        return np.array([0.0, 0.0])
    
    voxel = amr_box.GetCellData()
    den_data = voxel.GetArray("Density")
    if den_data is None:
        return np.array([0.0, 0.0])
    
    den_val = numpy_support.vtk_to_numpy(den_data)[0]
    num_points = amr_box.GetNumberOfPoints()
    vertices = amr_box.GetPoints()
    
    cell_center = np.zeros(3)
    for vertex in range(num_points):
        vert_coord = np.array(vertices.GetPoint(vertex))
        cell_center += vert_coord
    cell_center /= 8  # Average 8 vertices of cell
    
    # Fixed center at 0.25,0.25,0.25 (Sedov-specific)
    radial_distance = np.sqrt(
        (cell_center[0] - 0.25) ** 2 +
        (cell_center[1] - 0.25) ** 2 +
        (cell_center[2] - 0.25) ** 2
    )
    
    return np.hstack([den_val, radial_distance])


def process_single_vtk_file(args_tuple):
    """
    Process single VTKHDF file through complete AMR hierarchy.
    
    Args:
        args_tuple: Tuple of (args, output_number)
    """
    args, output_number = args_tuple
    
    folder_path = os.path.join(args.base_dir, args.folder_name)
    try:
        vtk_file = find_actual_vtk_file(folder_path, output_number)
    except FileNotFoundError as e:
        logger.warning("VTK file missing for %05d: %s", output_number, e)
        return
    
    logger.info("Processing: %s", vtk_file)
    
    # Read VTKHDF file
    hdf_reader = vtk.vtkHDFReader()
    hdf_reader.SetFileName(vtk_file)
    hdf_reader.Update()
    data = hdf_reader.GetOutput()
    
    if data is None:
        logger.error("Failed to read VTK file: %s", vtk_file)
        return
    
    # Process all AMR levels
    num_levels = data.GetNumberOfLevels()
    extracted_values = []
    
    for level in range(num_levels):
        num_blocks = data.GetNumberOfDataSets(level)
        logger.debug("Level %d: %d blocks", level, num_blocks)
        
        # Process blocks (serial within file for consistency)
        block_data = [find_density_cell(i, data, level) for i in range(num_blocks)]
        extracted_values.append(np.array(block_data))
    
    if not extracted_values:
        logger.warning("No data extracted from: %s", vtk_file)
        return
    
    # Aggregate all levels
    extracted_values = np.vstack(extracted_values)
    density_values = extracted_values[:, 0]
    rval, rinv = np.unique(extracted_values[:, 1], return_inverse=True)
    
    # Compute radial statistics
    den_mat = []
    for i, r in enumerate(rval):
        ridx = np.where(rinv == i)[0]
        den_mat.append(density_values[ridx])
    
    den_mean = [np.mean(arr) for arr in den_mat]
    den_std = [np.std(arr) for arr in den_mat]
    den_min = [np.min(arr) for arr in den_mat]
    den_max = [np.max(arr) for arr in den_mat]
    
    # HARDCODED: Always saves to ./profile_outputs/
    csv_path = Path("profile_outputs") / f"vtk_profile_{output_number:05d}.csv"
    os.makedirs(csv_path.parent, exist_ok=True)
    
    header = "Radius,Density_mean,Density_std,Density_min,Density_max"
    np.savetxt(str(csv_path), np.array([rval, den_mean, den_std, den_min, den_max]).T, 
               delimiter=",", header=header)
    logger.info("Saved: %s (%d bins)", csv_path, len(rval))


def run_serial(args, numbers: List[int]):
    """
    Serial execution mode (Windows-compatible).
    
    Args:
        args: CLI arguments
        numbers: Output numbers to process
    """
    logger.info("Running SERIAL mode")
    for num in numbers:
        try:
            process_single_vtk_file((args, num))
        except Exception as e:
            logger.error("Failed snapshot %d: %s", num, e)


def run_parallel(args, numbers: List[int]):
    """
    Parallel execution mode (Unix-compatible).
    
    Args:
        args: CLI arguments
        numbers: Output numbers to process
    """
    nproc = args.nproc or os.cpu_count() or 1
    logger.info("Running PARALLEL mode (%d cores)", nproc)
    with Pool(processes=nproc) as pool:
        pool.map(process_single_vtk_file, [(args, num) for num in numbers])


def main() -> None:
    """
    Main CLI entrypoint for VTK radial profile computation.
    """
    parser = argparse.ArgumentParser(
        description="VTK Radial Density Profiles from RAMSES VTKHDF files",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument("--base-dir", type=str, required=True, 
                       help="VTK root directory (e.g., '../vtk_outputs')")
    parser.add_argument("--folder-name", type=str, required=True, 
                       help="VTK simulation folder (e.g., 'sedov_3d')")
    parser.add_argument("-n", "--numbers", type=parse_output_numbers, default=None,
                       help="Output numbers (omit=ALL): '1', '1,3,5', '10-15'")
    parser.add_argument("--verbose", action="store_true", help="Verbose logging")
    parser.add_argument("--nproc", type=int, default=None, help="CPU cores (Unix)")

    args = parser.parse_args()

    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(levelname)s %(name)s: %(message)s"
    )

    # Normalize input path
    args.base_dir = os.path.abspath(args.base_dir)
    logger.info("VTK base directory: %s", args.base_dir)

    # Detect available VTK files
    all_outputs = detect_vtk_files(args.base_dir, args.folder_name)

    # Select snapshots
    if args.numbers is not None:
        numbers = match_short_numbers(args.numbers, all_outputs)
        if not numbers:
            logger.warning("No matches for %s. Using all available.", args.numbers)
            numbers = all_outputs
    else:
        numbers = all_outputs

    if not numbers:
        logger.info("No VTK files found to process.")
        return

    # HARDCODED OUTPUT: Always ./profile_outputs/
    output_dir = "profile_outputs"
    os.makedirs(output_dir, exist_ok=True)
    logger.info("Output directory: %s", os.path.abspath(output_dir))

    # Platform-specific execution
    try:
        if os.name == "nt":
            run_serial(args, numbers)
        else:
            run_parallel(args, numbers)
        logger.info("Completed: generated %d VTK profiles in %s", len(numbers), output_dir)
    except KeyboardInterrupt:
        logger.info("Interrupted by user")
    except Exception as e:
        logger.exception("Pipeline failed")


if __name__ == "__main__":
    main()
